test-job:
    stage: test
    image: python:latest
    tags:
        - docker
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - cd dresscode
        - python manage.py test
