# Generated by Django 3.1.3 on 2021-03-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dresscode_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
