# Generated by Django 3.1.2 on 2020-11-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresscode_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizzes',
            new_name='Quiz',
        ),
        migrations.RenameModel(
            old_name='QuizQuestions',
            new_name='QuizQuestion',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='answer',
            new_name='answer3',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='media1',
            new_name='media',
        ),
        migrations.AddField(
            model_name='poll',
            name='counter1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='counter2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='counter3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='reaction1_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='reaction2_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='reaction3_counter',
            field=models.IntegerField(default=0),
        ),
    ]
